### ISSUE TITLE
Using __local memory arguments in OpenCL kernel

### ISSUE THREAD

**Issue by luca825** [s-u/OpenCL#18]
Hello,

I'm trying to use a `__local` memory argument in a OpenCL kernel, for example:
```c
__kernel void testKernel(__global numeric* output, const unsigned int count, __global numeric* data, __local numeric* tmp, ) { 
// kernel code .... 
}
```
and then calling the kernel with the OpenCL R-Interface. 
```c
res = as.numeric(oclRun(kernel = k.test, size = Size, as.clBuffer(data, Context)))
```

But if I have the `__local` argument in the kernel, I get the error `CL_INVALID_KERNEL_ARGS`. I tried to give a `clBuffer` object in the form I want the `__local` argument, but I did not get it to work either. Is their a possibility to run the kernel with the OpenCL-R Interface, while having a local memory argument in the kernel?

**Comment by aaronpuchert** [comment]
We cannot pass data to a `__local` pointer parameter, to quote the [documentation](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/clSetKernelArg.html) for `clSetKernelArg`:

> If the argument is declared with the [__local](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/local.html) qualifier, the `arg_value` entry must be NULL.

And:

> For arguments declared with the [__local](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/local.html) qualifier, the size specified will be the size in bytes of the buffer that must be allocated for the [__local](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/local.html) argument.

We could probably introduce a special placeholder for this. Like `clLocalMemory(1024, "numeric")`, and then we'd pass `1024 * sizeof(numeric)` as size.

However, if the size is constant, you can also just add something like
```c
__local numeric tmp[256];
```
The parameter is only needed if you don't know the `__local` buffer size at compile time.

**Comment by luca825** [comment]
Thanks for the answer! Unfortunately I don't know the __local buffer size at compile time, instead I will try to implement my kernel without the __local memory for the moment, but I would greatly appreciate, if in the future the OpenCL R-Interface would allow to use __local memory!

**Comment by s-u** [comment]
Although I'm still not convinced there is any use-case for dynamically allocated local memory (since its usability is limited by group size in practice anyway so can pretty much always be statically allocated - you have access to more information in the kernel at compile time than at run-time in R) I have added support for it via the `clLocal()` function along the lines of what Aaron mentioned above so your code should work with

```r
res = as.numeric(oclRun(kernel = k.test, size = Size,
                 as.clBuffer(data, Context), clLocal(len, "numeric")))
```

Please note that you will still need to use barriers to access local memory across threads, so this opens a whole can of worms and thus should only be used by expert OpenCL users!
